----------------Data Query language-----------
use FnFTraining
select * from tblEmployee

Select EmpName, EmpSalary from tblEmployee

--MAX MIN TOP, AVG are called as Scalar Value Functions(SVFs) that return only one value from the expression. 
Select Max(EmpSalary) as MaxSalary, Min(EmpSalary) as MinSalary, AVG(EmpSalary) as AvgSalary from tblEmployee 

Select Top(100) EmpName from tblEmployee

Select Top  25 PERCENT * from tblEmployee

--Get the Bottom 25 % from tblEmployee
Select Top 25 Percent * from tblEmployee Order by EmpId DESC--This works only if the ID is Autogenerated. 

Select * From
(
Select Top 25 Percent * from tblEmployee Order by EmpId DESC
) TEMP  ORDER BY EmpID ASC
------------------------------------WHERE-------------------------------
Select * from tblEmployee Where CityId < 5
Select Empname from tblEmployee where empname like '%a%'
Select Empname, EmpSalary from tblEmployee where EmpSalary between 30000 and 70000 order by EmpSalary

Select EmpName From tblEmployee Where CityId = 5 or CityId = 6
Select * from tblCity
----------------------------------JOINS-------------------------------
Select tblEmployee.EmpName, tblEmployee.EmpEmail, tblEmployee.EmpSalary, tblCity.CityName from tblEmployee JOIN tblCity on tblEmployee.CityId = tblCity.CityId
Where tblCity.CityName = 'Bangalore'
ORDER BY EmpName

---Update the tblEmployee with few rows with CityId as null for example on LEFT JOIN
Update tblEmployee
Set CityId = NULL where EmpID = 654

Select * from tblEmployee where CityId is null

Insert into tblCity Values('London')
Insert into tblCity Values('Dharwad')

Select * from tblCity
---------------Left Join gets all rows of 1st table along with matching records from the 2nd Table
Select tblEmployee.*, tblCity.CityName from tblEmployee LEFT JOIN tblCity 
ON tblEmployee.CityId = tblCity.CityId
--Right join is opp of Left Join
Select tblEmployee.*, tblCity.CityName from tblEmployee RIGHT JOIN tblCity 
ON tblEmployee.CityId = tblCity.CityId


---Some Joins examples------------------
--Get the CityName and Max Salary for each City.
Select tblCity.CityName, MAX(tblEmployee.EmpSalary) as MaxSalary From tblEmployee 
Right Join tblCity
ON tblEmployee.CityId = tblCity.CityId
Group by tblCity.CityName
--Get the DeptName with Total Salaries of each Dept. 
Select tblDept.DeptName, SUM(tblEmployee.EmpSalary) as TotalSalaries from tblEmployee
RIGHT join tblDept
on tblEmployee.DeptId = tblDept.DeptId
Group by tblDept.DeptName

--Get the EmpName, DeptName and CityName of each Employee. 
Select tblEmployee.EmpName,  tblDept.DeptName, tblCity.CityName from tblEmployee
Right Join tblDept 
On  tblEmployee.DeptId = tblDept.DeptId
RIGHT JOIN tblCity
ON tblEmployee.CityId = tblCity.CityId

--Get the EmpName of the Employee who has the Max salary of that dept and also the city where he stays. 

--Get the Emp Count of each Dept using GROUP BY CLAUSE
Select tblDept.DeptName, COUNT(tblEmployee.EmpId) as EmpCount from tblEmployee
Right join tblDept
On tblEmployee.DeptId = tblDept.DeptId
group by tblDept.DeptName
Order by EmpCount DESC

--Get the Employees whose Salary is greater than the Avg salary of his dept. 
--Get the EmpCount whose salary is greater than 100000
Select Count(tblEmployee.EmpId) as EmpCount, tblEmployee.EmpSalary from tblEmployee
Group By EmpSalary
Having EmpSalary between 50000 and 100000

Select EmpName, EmpSalary  from tblEmployee Where Empsalary > (SELECT AVG(EmpSalary) From tblEmployee)


